#include<stdio.h>
void print_desc_box(const char * testo, int nchar);
void print_invisible_box(const char * testo, int nchar);
void print_dialogue_box(const char * testo, int nchar);
void printLine(int nchar);
void clean_fgets(char * stringa, int maxlenght,FILE * filename);
int oggetto_(char * subazione);
int incantesimo_(char * subazione);
int spostamento_(char * dir);
int azione_ (char * action);
int scelta_(char * s);
int attack_(char * s);
int defense_(char * stringa);
int escape_(char * scelta);
int decode (char * string, int (*mode)(char *));
void ask(char * testo);
void print_star_Line(int nchar);
void print_star_box(const char * testo, int nchar);
void print_double_dot_line(int nchar);
void print_dot_line(int nchar);
void print_square_box(const char * testo, int nchar);
void printLine_noStar(int nchar);
void print_intro(void);
void print_debug(void);
void print_credits(void);
void printSettings(sett* settings);
void printSet(char* setting, short isOn);
void bell(int times, sett* settings);
void change_settings(sett*settings);